# Generated by Django 3.0.8 on 2020-07-12 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_current_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='current_bid',
            new_name='bid_value',
        ),
        migrations.AddField(
            model_name='bid',
            name='by_user',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='bids_made', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bid',
            name='for_listing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bids_received', to='auctions.Listing'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='auctions.Category'),
            preserve_default=False,
        ),
    ]
