# Generated by Django 3.0.8 on 2020-07-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200712_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='increment',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
