# Generated by Django 3.0.8 on 2020-07-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_bid_increment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='increment',
        ),
        migrations.AddField(
            model_name='listing',
            name='increment',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
