# Generated by Django 3.0.8 on 2020-07-13 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20200713_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='bid_increment',
            new_name='bid_increment',
        ),
    ]
