# Generated by Django 3.0.8 on 2020-07-17 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20200715_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='winning_bid',
            field=models.BooleanField(default=False),
        ),
    ]
