# Generated by Django 3.0.8 on 2020-07-19 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auto_20200719_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo_url',
            field=models.URLField(blank=True, default='https://d1nhio0ox7pgb.cloudfront.net/_img/i_collection_png/48x48/plain/objects.png', null=True),
        ),
    ]
